# Generated by wallust — sourced by the wallpaper picker. Universal variables
# (set -U) propagate to every running fish instance, so prompts/syntax recolor
# live. Accent is orange; foreground follows the wallpaper.
set -U wallust_accent F08A3C
set -U wallust_accent_bright FFB066
set -U wallust_fg {{foreground | strip}}

set -U fish_color_command {{foreground | strip}}
set -U fish_color_param F08A3C
set -U fish_color_quote 98C379
set -U fish_color_redirection FFB066
set -U fish_color_end FFB066
set -U fish_color_operator FFB066
set -U fish_color_autosuggestion C56A24
set -U fish_color_comment C56A24
set -U fish_color_error FF7A85
set -U fish_color_escape FFB066
