# Personal overrides — sourced after base config
# Variable reference: https://wiki.hyprland.org/Configuring/Variables/

decoration:blur:enabled = 0
decoration:blur:xray = 0
decoration:blur:size = 7
animations:enabled = 0
debug:enable_stdout_logs = 0
