# exec = export SLURP_ARGS='-d -c E2E2E2BB -b 47474744 -s 00000000'

general {
    col.active_border = rgba(E2E2E239)
    col.inactive_border = rgba(91919130)
}

misc {
    background_color = rgba(131313FF)
}

windowrule = bordercolor rgba(FFFFFFAA) rgba(FFFFFF77), pinned:1